FROM node:12-alpine

WORKDIR /srv

COPY . .

RUN npm ci --production
RUN npm install -g gulp
RUN gulp build

ENV NODE_ENV production
ENV GOOGLE_APPLICATION_CREDENTIALS AtvSignum-1c4664191a58.json
ENV PORT 80
ENV DB_PORT 3306
ENV DB_NAME ATV
ENV DB_USERNAME DB-ATV
ENV DB_PASSWORD vmUUaF^4zS6nfSa7VzkGJJTfsBGj7nz&e&vNW&ce9FVH6CqG%yNaeCnez!85vnSE#Ew@GWXu5!q
ENV DB_HOST 35.223.55.134
ENV DB_DIALECT mysql
ENV SESSION_KEY SID
ENV SESSION_SECRET ATVATV

EXPOSE $PORT

ENTRYPOINT ["node", "./src/server.js"]
