#Auth Requests#
POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "cafer",
    "password": "12345"
}
###
GET http://localhost:3000/auth/login
###
GET http://localhost:3000/auth/logout

#Vehicle Requests#

###
GET http://localhost:3000/vehicle/add
###
POST http://localhost:3000/vehicle/add
content-type: application/json

{
    "plate": "VV",
    "chassisNo": "test",
    "trusteeNo": "test",
    "vehicleTypeId": "2",
    "engineNo": "test",
    "colorId": "3",
    "modelYear": "2011",
    "bodyTypeId": "3",
    "brandId": "2",
    "ownerProfileId": "3"
}
###
GET http://localhost:3000/vehicle/search
###
POST http://localhost:3000/vehicle/search
content-type: application/json

{
    "plate": "VV"
}
###
GET http://localhost:3000/competency/add
###
POST http://localhost:3000/competency/add
content-type: application/json

{
    "description": "sokusabilir"
}

###
GET http://localhost:3000/competency/list
###
POST http://localhost:3000/competency/delete
content-type: application/json

{
    "description": "sikisebilir"
}
